### ISSUE TITLE
Alteração favicon

### ISSUE THREAD

**Issue by luizcsbh** [sineto/gogama.now.sh#1]
Alterar o arquivo favicon padrão do react que encontra na página /public/favicon.ico por um que tem haver com layout da página. No endereço http://www.favicon.pro/pt/ gera favicon apartir de uma imagem

**Comment by sineto** [comment]
Issue resolvida via commit https://github.com/sineto/gogama.now.sh/commit/4ba80688729d1bfab1cc45c7eb0584a325c6f1f6
