### ISSUE TITLE
Alteração da meta description

### ISSUE THREAD

**Issue by luizcsbh** [sineto/gogama.now.sh#2]
Alterar as informações no arquivo localizado /public/index.html na tag meta description com as informações referente ao projeto, uma sugestão de texto: content: "Web site do grupo Impossíveis no programa Hiring Coders"

**Comment by sineto** [comment]
Issue resolvida pelo commit https://github.com/sineto/gogama.now.sh/commit/c98fd3dc0e5c1ce9e7782d4d8ae0b1e5834eea5b e https://github.com/sineto/gogama.now.sh/commit/4ba80688729d1bfab1cc45c7eb0584a325c6f1f6
